PresentationLogic/Models/Desperfecto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PresentationLogic.Models
{
    public class Desperfecto
    {
        public int IdDesperfecto { get; set; }
        public int IdVehiculo { get; set; }
        public string Descripcion { get; set; }
        public double ManoObra { get; set; }
        public int TiempoDias { get; set; }
    }
}

PresentationLogic/Models/Repuesto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLogic.Models
{
    public class Repuesto
    {
        public int IdRepuesto { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
    }
}

PresentationLogic/Models/Vehiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PresentationLogic.Models
{
    public abstract class Vehiculo
    {
        public int IdVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }

        public string Patente { get; set; }
    }
}

PresentationLogic/Controllers/DesperfectoController.cs
using PresentationLogic.Models;
using PresentationLogic.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLogic.Controllers
{
    public class DesperfectoController : Controller
    {
        private readonly IDesperfectoService _desperfectoService;

        public DesperfectoController()
        {
            _desperfectoService = new DesperfectoService(ConfigurationManager.ConnectionStrings["ChallengeRecruitingDB"].ConnectionString);
        }
        // GET: Desperfecto
        public ActionResult Index()
        {
            var lDesperfectos = _desperfectoService.GetAllDesperfectos();

            return View(lDesperfectos);
        }

        // GET: Repuesto/Details/5
        public ActionResult Details(int id)
        {
            Desperfecto desperfecto = null;
            try
            {
                desperfecto = _desperfectoService.GetDesperfecto(id);
            }
            catch (Exception ex) { }

            return View(desperfecto);
        }

        public ActionResult Vehiculos(int id)
        {
            var lDesperfectos = _desperfectoService.GetDesperfectosFromVehiculo(id);

            return View(lDesperfectos);
        }

        public ActionResult Repuestos(int id)
        {
            var lDesperfectos = _desperfectoService.GetDesperfectosFromRepuesto(id);

            return View(lDesperfectos);
        }

        // GET: Desperfecto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Desperfecto/Create
        [HttpPost]
        public ActionResult Create(Desperfecto desperfectoToInsert)
        {
            try
            {
                _desperfectoService.InsertDesperfecto(desperfectoToInsert);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Desperfecto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Desperfecto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Desperfecto desperfectoToUpdate)
        {
            try
            {
                desperfectoToUpdate.IdDesperfecto = id;
                _desperfectoService.UpdateDesperfecto(desperfectoToUpdate);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Desperfecto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Desperfecto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Desperfecto desperfectoToDelete)
        {
            try
            {
                _desperfectoService.DeleteDesperfecto(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PresentationLogic/Controllers/RepuestoController.cs
using PresentationLogic.Models;
using PresentationLogic.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLogic.Controllers
{
    public class RepuestoController : Controller
    {
        private readonly IRepuestoService _repuestoService;

        public RepuestoController()
        {
            _repuestoService = new RepuestoService(ConfigurationManager.ConnectionStrings["ChallengeRecruitingDB"].ConnectionString);
        }

        // GET: Repuesto
        public ActionResult Index()
        {
            var lRepuestos = _repuestoService.GetAllRepuestos();

            return View(lRepuestos);
        }

        public ActionResult Desperfecto(int id)
        {
            var lRepuestos = _repuestoService.GetRepuestosFromDesperfecto(id);

            return View(lRepuestos);
        }

        // GET: Repuesto/Details/5
        public ActionResult Details(int id)
        {
            var repuesto = _repuestoService.GetRepuesto(id);

            return View(repuesto);
        }

        // GET: Repuesto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Repuesto/Create
        [HttpPost]
        public ActionResult Create(Repuesto repuestoToInsert)
        {
            try
            {
                _repuestoService.InsertRepuesto(repuestoToInsert);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Repuesto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Repuesto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Repuesto repuestoToUpdate)
        {
            try
            {
                repuestoToUpdate.IdRepuesto = id;
                _repuestoService.UpdateRepuesto(repuestoToUpdate);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Repuesto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Repuesto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Repuesto repuestoToDelete)
        {
            try
            {
                _repuestoService.DeleteRepuesto(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PresentationLogic/Views/Desperfecto/Create.cshtml
@model PresentationLogic.Models.Desperfecto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Desperfecto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.IdVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManoObra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManoObra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManoObra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TiempoDias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TiempoDias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TiempoDias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLogic/Views/Desperfecto/Delete.cshtml
@model PresentationLogic.Models.Desperfecto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Desperfecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdDesperfecto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdDesperfecto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManoObra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManoObra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TiempoDias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TiempoDias)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PresentationLogic/Views/Desperfecto/Details.cshtml
@model PresentationLogic.Models.Desperfecto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Desperfecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdDesperfecto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdDesperfecto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManoObra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManoObra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TiempoDias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TiempoDias)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.IdDesperfecto  }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PresentationLogic/Views/Desperfecto/Edit.cshtml
@model PresentationLogic.Models.Desperfecto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Desperfecto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.IdVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManoObra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManoObra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManoObra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TiempoDias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TiempoDias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TiempoDias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLogic/Views/Desperfecto/Index.cshtml
@model IEnumerable<PresentationLogic.Models.Desperfecto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdDesperfecto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManoObra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TiempoDias)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdDesperfecto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdVehiculo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManoObra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TiempoDias)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.IdDesperfecto }) |
            @Html.ActionLink("Details", "Details", new { id = item.IdDesperfecto }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IdDesperfecto }) |
            @Html.ActionLink("Repuestos", "Desperfecto", "Repuesto", new { id = item.IdDesperfecto }, null)
        </td>
    </tr>
}

</table>

PresentationLogic/Views/Desperfecto/Repuestos.cshtml
@model IEnumerable<PresentationLogic.Models.Desperfecto>

@{
    ViewBag.Title = "Repuestos";
}

<h2>Repuestos</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdDesperfecto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManoObra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TiempoDias)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdDesperfecto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdVehiculo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManoObra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TiempoDias)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.IdDesperfecto }) |
            @Html.ActionLink("Details", "Details", new { id = item.IdDesperfecto }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IdDesperfecto })
        </td>
    </tr>
}

</table>

PresentationLogic/Views/Desperfecto/Vehiculos.cshtml
@model IEnumerable<PresentationLogic.Models.Desperfecto>

@{
    ViewBag.Title = "Vehiculos";
}

<h2>Vehiculos</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdDesperfecto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManoObra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TiempoDias)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdDesperfecto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdVehiculo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManoObra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TiempoDias)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.IdDesperfecto }) |
            @Html.ActionLink("Details", "Details", new { id = item.IdDesperfecto }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IdDesperfecto })
        </td>
    </tr>
}

</table>